eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-54-163-190-29.compute-1.amazonaws.com:8761/eureka
  instance:
    hostname: ec2-54-163-190-29.compute-1.amazonaws.com
