eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-54-90-65-14.compute-1.amazonaws.com:8761/eureka

  instance:
    hostname: localhost
